// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MH.PLCM.Core.Entities
{
    public partial class AppMenuItem
    {
        public AppMenuItem()
        {
            Children = new HashSet<AppMenuItem>();
        }

        [Key]
        public int Id { get; set; }
        [StringLength(50)]
        public string MenuText { get; set; }
        [StringLength(255)]
        public string LinkUrl { get; set; }
        [StringLength(100)]
        public string CssClassForIcon { get; set; }
        public int MenuOrder { get; set; }
        public int ParentMenuItemId { get; set; }
        public int? MenuId { get; set; }

        [ForeignKey(nameof(MenuId))]
        [InverseProperty(nameof(AppMenuItem.Children))]
        public virtual AppMenuItem Menu { get; set; }
        [InverseProperty(nameof(AppMenuItem.Menu))]
        public virtual ICollection<AppMenuItem> Children { get; set; }
    }
}