// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MH.PLCM.Core.Entities
{
    public partial class AppPermission
    {
        public AppPermission()
        {
            AppRolePermissions = new HashSet<AppRolePermission>();
            Children = new HashSet<AppPermission>();
        }

        [Key]
        public int PermissionId { get; set; }
        [Required]
        [StringLength(100)]
        public string Name { get; set; }
        [Required]
        [StringLength(150)]
        public string Code { get; set; }
        public int? ParentId { get; set; }
        [StringLength(250)]
        public string Remarks { get; set; }

        [ForeignKey(nameof(ParentId))]
        [InverseProperty(nameof(AppPermission.Children))]
        public virtual AppPermission Parent { get; set; }
        [InverseProperty(nameof(AppRolePermission.Permission))]
        public virtual ICollection<AppRolePermission> AppRolePermissions { get; set; }
        [InverseProperty(nameof(AppPermission.Parent))]
        public virtual ICollection<AppPermission> Children { get; set; }
    }
}