// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MH.PLCM.Core.Entities
{
    [Table("AppRolePermission")]
    public partial class AppRolePermission
    {
        [Key]
        public int AppRoleId { get; set; }
        [Key]
        public int PermissionId { get; set; }

        [ForeignKey(nameof(AppRoleId))]
        [InverseProperty("AppRolePermissions")]
        public virtual AppRole AppRole { get; set; }
        [ForeignKey(nameof(PermissionId))]
        [InverseProperty(nameof(AppPermission.AppRolePermissions))]
        public virtual AppPermission Permission { get; set; }
    }
}