// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MH.PLCM.Core.Entities
{
    [Table("AppUserRole")]
    public partial class AppUserRole
    {
        [Key]
        public string Id { get; set; }
        [Key]
        public int AppRoleId { get; set; }

        [ForeignKey(nameof(AppRoleId))]
        [InverseProperty("AppUserRoles")]
        public virtual AppRole AppRole { get; set; }
        [ForeignKey(nameof(Id))]
        [InverseProperty(nameof(ApplicationUser.AppUserRoles))]
        public virtual ApplicationUser IdNavigation { get; set; }
    }
}