// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MH.PLCM.Core.Entities
{
    public partial class DynamicItemFeature
    {
        [Key]
        [Column("RowID")]
        public int RowId { get; set; }
        [Column("ItemRowID")]
        public int ItemRowId { get; set; }
        [Column("FeatureRowID")]
        public int FeatureRowId { get; set; }
        [Required]
        [StringLength(1000)]
        public string FeatureValue { get; set; }
        [Required]
        [StringLength(100)]
        public string Comments { get; set; }
        public int Sequence { get; set; }

        [ForeignKey(nameof(FeatureRowId))]
        [InverseProperty(nameof(DynamicFeature.DynamicItemFeatures))]
        public virtual DynamicFeature FeatureRow { get; set; }
        [ForeignKey(nameof(ItemRowId))]
        [InverseProperty(nameof(DynamicItem.DynamicItemFeatures))]
        public virtual DynamicItem ItemRow { get; set; }
    }
}