// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MH.PLCM.Core.Entities
{
    public partial class DynamicTemplateFeature
    {
        [Key]
        [Column("RowID")]
        public int RowId { get; set; }
        [Column("TemplateRowID")]
        public int TemplateRowId { get; set; }
        [Column("FeatureRowID")]
        public int FeatureRowId { get; set; }
        [Required]
        [StringLength(1000)]
        public string FeatureValue { get; set; }

        [ForeignKey(nameof(TemplateRowId))]
        [InverseProperty(nameof(DynamicTemplate.DynamicTemplateFeatures))]
        public virtual DynamicTemplate TemplateRow { get; set; }
    }
}