// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MH.PLCM.Core.Entities
{
    public partial class DynamicItem
    {
        public DynamicItem()
        {
            DynamicItemFeatures = new HashSet<DynamicItemFeature>();
        }

        [Key]
        [Column("RowID")]
        public int RowId { get; set; }
        public int EntityTypeId { get; set; }
        public int? EntityKeyId { get; set; }

        [InverseProperty(nameof(DynamicItemFeature.ItemRow))]
        public virtual ICollection<DynamicItemFeature> DynamicItemFeatures { get; set; }
    }
}