// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MH.PLCM.Core.Entities
{
    public partial class DynamicFeature
    {
        public DynamicFeature()
        {
            DynamicItemFeatures = new HashSet<DynamicItemFeature>();
        }

        [Key]
        [Column("RowID")]
        public int RowId { get; set; }
        [Required]
        [StringLength(100)]
        public string Description { get; set; }

        [Column("DataTypeID")]
        public FeatureDataType DataTypeId { get; set; }

        [Column("LookupID")]
        public int? LookupId { get; set; }

        [Column("ReportGroupID")]
        public int ReportGroupId { get; set; }
        public int GroupOrder { get; set; }
        [StringLength(50)]
        public string DefaultValue { get; set; }
        [StringLength(50)]
        public string UnitOfMeasure { get; set; }
        public bool IsBaanFeature { get; set; }
        [Column("ResponsibleGroupID")]
        public int ResponsibleGroupId { get; set; }
        [Required]
        public bool? Active { get; set; }  

        [InverseProperty(nameof(DynamicItemFeature.FeatureRow))]
        public virtual ICollection<DynamicItemFeature> DynamicItemFeatures { get; set; }
    }
}