// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MH.PLCM.Models
{
    [Table("NACO_Filter")]
    public partial class NacoFilter
    {
        [Key]
        public long Id { get; set; }
        [StringLength(15)]
        public string ElementLength { get; set; }
        [StringLength(15)]
        public string ElementHeight { get; set; }
        [StringLength(15)]
        public string ElementWidth { get; set; }
        public int? ElementThread { get; set; }
        [StringLength(15)]
        public string FilterWeight { get; set; }
        [StringLength(15)]
        public string OuterDiameterTop { get; set; }
        [StringLength(15)]
        public string InnerDiameterTop { get; set; }
        [StringLength(15)]
        public string OuterDiameterBottom { get; set; }
        [StringLength(15)]
        public string InnerDiameterBottom { get; set; }
        [StringLength(15)]
        public string Other { get; set; }
        public int? ElementIdentinfication { get; set; }
        public long? PaintColorId { get; set; }
        public int? PaintPartNumber { get; set; }
        public int? Inkcolor1 { get; set; }
        public int? InkpartNumber1 { get; set; }
        public int? Inkcolor2 { get; set; }
        public int? InkpartNumber2 { get; set; }
        [StringLength(2500)]
        public string Identification { get; set; }
        [StringLength(50)]
        public string PaintPlateIdentification { get; set; }
        public int? PlateOrientation { get; set; }
        [Required]
        [Column("IDMethodId")]
        [StringLength(50)]
        public string IdmethodId { get; set; }
        [Required]
        [StringLength(50)]
        public string PrintPlate1PartNo { get; set; }
        [Required]
        [StringLength(50)]
        public string PrintPlate2PartNo { get; set; }
        [Required]
        [StringLength(50)]
        public string MasterPlatePartNo { get; set; }
        [Required]
        [StringLength(50)]
        public string InnerDiameterLabelPartNo { get; set; }
    }
}