// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MH.PLCM.Models
{
    [Table("NACO_Trigger")]
    public partial class NacoTrigger
    {
        [Key]
        public long Id { get; set; }
        public long ChangeOrderId { get; set; }
        public long? FromUserId { get; set; }
        public int? ToUserId { get; set; }
        [Required]
        [StringLength(200)]
        public string What { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedOn { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ActionTookOn { get; set; }
        [StringLength(50)]
        public string Department { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastReminderOn { get; set; }
        public int? RemindDays { get; set; }
    }
}