// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MH.PLCM.Models
{
    [Table("NACO_EngArtworkRequest")]
    public partial class NacoEngArtworkRequest
    {
        public NacoEngArtworkRequest()
        {
            NacoEngArtworkRequestPlates = new HashSet<NacoEngArtworkRequestPlate>();
        }

        [Key]
        public long Id { get; set; }
        public int? IsNewPart { get; set; }
        public int? RequestorId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ArtWorkOn { get; set; }
        [StringLength(30)]
        public string Height { get; set; }
        [Column(TypeName = "decimal(8, 4)")]
        public decimal? PanelCenterLine { get; set; }
        public long? FilterTypeId { get; set; }
        public int? NumOfTurns { get; set; }
        public int? Style { get; set; }
        public int? Panel1 { get; set; }
        public int? Panel2 { get; set; }
        public int? Panel3 { get; set; }
        public int? Panel4 { get; set; }
        public int? BackPanel { get; set; }
        public int? TorqueNumbers { get; set; }
        public int? CautionStatement { get; set; }
        [StringLength(50)]
        public string RunOnLine { get; set; }
        public int? PlateOrientation { get; set; }
        [StringLength(50)]
        public string DoubleseamLocation { get; set; }
        [Column(TypeName = "ntext")]
        public string SpecialInstructions { get; set; }
        public int? IsUlListing { get; set; }

        [InverseProperty(nameof(NacoEngArtworkRequestPlate.ArkworkRequest))]
        public virtual ICollection<NacoEngArtworkRequestPlate> NacoEngArtworkRequestPlates { get; set; }
    }
}