// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MH.PLCM.Models
{
    [Table("NACO_History")]
    public partial class NacoHistory
    {
        [Key]
        public long Id { get; set; }
        public long? ChangeOrderId { get; set; }
        public int? ChangingUserId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ChangedOn { get; set; }
        [StringLength(500)]
        public string ChangeDescription { get; set; }
        [StringLength(250)]
        public string Filename { get; set; }
    }
}