// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MH.PLCM.Models
{
    [Table("NACO_Quality")]
    public partial class NacoQuality
    {
        [Key]
        public long Id { get; set; }
        public int? IsComplete { get; set; }
        [Column(TypeName = "decimal(8, 4)")]
        public decimal? PackHeight { get; set; }
        [Column(TypeName = "decimal(8, 4)")]
        public decimal? PackLength { get; set; }
        [Column(TypeName = "decimal(8, 4)")]
        public decimal? PackWidth { get; set; }
        [StringLength(50)]
        public string PackWeight { get; set; }
        public bool? IsChkdGraphicIdentCorrect { get; set; }
        public bool? IsChkdLblCorrect { get; set; }
        public bool? IsChkdBarcodeCorrect { get; set; }
        public bool? IsChkdBoxCorrect { get; set; }
        public bool? IsChkdFilterBoxCloses { get; set; }
        public bool? IsChkdPackAccToPrint { get; set; }
        public bool? IsChkdPalletDetailCorrect { get; set; }
        [StringLength(50)]
        public string StandardPackWeight { get; set; }
        [Column(TypeName = "ntext")]
        public string AdditionalNotes { get; set; }
        public bool? IsChkdfilterBox { get; set; }
        public bool? IsChkdToPrint { get; set; }
        public bool? IsChkdBoxCloses { get; set; }
        public bool? IsChkdPalletDetail { get; set; }
    }
}