// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MH.PLCM.Models
{
    [Table("NACO_EngArtworkRequestPlate")]
    public partial class NacoEngArtworkRequestPlate
    {
        [Key]
        public long Id { get; set; }
        public long ArkworkRequestId { get; set; }
        [StringLength(50)]
        public string CatalogNumber { get; set; }
        public long? AccountId { get; set; }
        [StringLength(50)]
        public string Numbers99 { get; set; }
        [Column("ulApproved")]
        public int? UlApproved { get; set; }
        [StringLength(50)]
        public string Remarks { get; set; }
        [Column("filetype")]
        [StringLength(50)]
        public string Filetype { get; set; }

        [ForeignKey(nameof(ArkworkRequestId))]
        [InverseProperty(nameof(NacoEngArtworkRequest.NacoEngArtworkRequestPlates))]
        public virtual NacoEngArtworkRequest ArkworkRequest { get; set; }
    }
}