// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MH.PLCM.Models
{
    [Table("NACO_PackagingValImages")]
    public partial class NacoPackagingValImage
    {
        [Key]
        public long Id { get; set; }
        public long ChangeOrderId { get; set; }
        [StringLength(50)]
        public string FileName { get; set; }
        public int? UploadedById { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UploadedOn { get; set; }
    }
}