// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MH.PLCM.Models
{
    [Table("NACO_Packaging")]
    public partial class NacoPackaging
    {
        [Key]
        public long Id { get; set; }
        [StringLength(50)]
        public string BoxNum { get; set; }
        [StringLength(50)]
        public string BoxPrint { get; set; }
        [StringLength(50)]
        public string BoxGraphics { get; set; }
        [StringLength(50)]
        public string BoxSize { get; set; }
        [StringLength(50)]
        public string BoxMaterial { get; set; }
        [StringLength(50)]
        public string BoxLabel { get; set; }
        [StringLength(50)]
        public string BoxCountry { get; set; }
        [StringLength(50)]
        public string CartonNum { get; set; }
        [StringLength(50)]
        public string CartonGraphics { get; set; }
        [StringLength(50)]
        public string CartonSize { get; set; }
        [StringLength(50)]
        public string CartonQty { get; set; }
        [StringLength(50)]
        public string CartonLabel { get; set; }
        [StringLength(50)]
        public string CartonLabelQty { get; set; }
        [StringLength(50)]
        public string CartonStenmark { get; set; }
        [StringLength(50)]
        public string CartonCountry { get; set; }
        [StringLength(50)]
        public string CartonOther { get; set; }
        [StringLength(50)]
        public string ProtectiveWrapStyle { get; set; }
        [StringLength(50)]
        public string ProtectiveWrapPartNum { get; set; }
        [StringLength(50)]
        public string ProtectiveWrapSize { get; set; }
        [StringLength(50)]
        public string ProtectiveWrapQuantity { get; set; }
        [StringLength(50)]
        public string ProtectiveWrapLabel { get; set; }
        [StringLength(50)]
        public string ProtectiveWrapLabelQty { get; set; }
        [StringLength(50)]
        public string ProtectiveWrapCountry { get; set; }
        [StringLength(50)]
        public string ProtectiveWrapCartonLabel { get; set; }
        [StringLength(50)]
        public string ProtectiveWrapBoxLabel { get; set; }
        [StringLength(50)]
        public string ProtectiveWrapOther { get; set; }
        [StringLength(50)]
        public string PalletDetail { get; set; }
        [StringLength(50)]
        public string PalletDetailNum { get; set; }
        [StringLength(50)]
        public string PalletCartons { get; set; }
        public int? PalletNumLayers { get; set; }
        [StringLength(20)]
        public string PalletQty { get; set; }
        [StringLength(20)]
        public string PalletLabel { get; set; }
        [StringLength(8)]
        public string PalletLabelQty { get; set; }
        [StringLength(50)]
        public string PalletCountry { get; set; }
        [StringLength(50)]
        public string PalletPartitions1 { get; set; }
        [StringLength(50)]
        public string PalletPartitions1Qty { get; set; }
        [StringLength(50)]
        public string PalletPartitions2 { get; set; }
        [StringLength(50)]
        public string PalletPartitions2Qty { get; set; }
        [StringLength(50)]
        public string PalletCapacity { get; set; }
        [StringLength(50)]
        public string PalletCapacityQty { get; set; }
        [StringLength(50)]
        public string PalletTube { get; set; }
        [StringLength(50)]
        public string PalletTubeQty { get; set; }
        [StringLength(50)]
        public string PalletPad { get; set; }
        [StringLength(50)]
        public string PalletPadQty { get; set; }
        [StringLength(50)]
        public string PalletBottomPad { get; set; }
        [StringLength(5000)]
        public string OtherPackaging { get; set; }
        public int? IsUpcPrefix { get; set; }
        [StringLength(50)]
        public string Upc { get; set; }
        [StringLength(50)]
        public string I2of5 { get; set; }
        [Column("3of9")]
        [StringLength(50)]
        public string _3of9 { get; set; }
        public long? BarCodeId { get; set; }
        public int? IsRoundFullCarton { get; set; }
        public long? StdPackId { get; set; }
        public int? PrintingPlateNumber { get; set; }
        [StringLength(50)]
        public string DateCodeSpec { get; set; }
        public int? StdSkId { get; set; }
        public bool? PackagingVerified { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? PackagingVerifiedOn { get; set; }
        public int? PackagingVerifiedBy { get; set; }
    }
}