// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MH.PLCM.Models
{
    [Table("NACO_MSS")]
    public partial class NacoMss
    {
        [Key]
        public long Id { get; set; }
        [Column("ActualEOQ")]
        public int? ActualEoq { get; set; }
        public int? ActualInitialRun { get; set; }
        public long? PlannerId { get; set; }
        public long? SelectionCodeId { get; set; }
        public long? OrderIntervalId { get; set; }
        public long? BillOfLadingId { get; set; }
        [Column("NOQMOQ")]
        public int? Noqmoq { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ScheduledOn { get; set; }
        public float? ActualStandardCost { get; set; }
    }
}