// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MH.PLCM.Models
{
    [Table("NACO_Validations")]
    public partial class NacoValidation
    {
        [Key]
        public long Id { get; set; }
        public long? ChangeOrderId { get; set; }
        public long? ValidationId { get; set; }
        public bool? IsRequired { get; set; }
        public bool? IsComplete { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CompletedOn { get; set; }
        public int? CompletedById { get; set; }
    }
}