// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MH.PLCM.Models
{
    [Table("NACO_Engineering")]
    public partial class NacoEngineering
    {
        [Key]
        public long Id { get; set; }
        public int? IsUlListing { get; set; }
        public int? IsPurchasedProduct { get; set; }
        [StringLength(50)]
        public string SupplierPartNumber { get; set; }
        [StringLength(50)]
        public string ManufacturerPartNumber { get; set; }
        [StringLength(50)]
        public string PurchasedEleSupplier { get; set; }
        public long? PackagingFilterTypeId { get; set; }
        [Column("IsPPAPRequired")]
        public int? IsPpaprequired { get; set; }
        [Column("PPAPLevelId")]
        public long? PpaplevelId { get; set; }
        [Column("PPAPDueDateOn", TypeName = "datetime")]
        public DateTime? PpapdueDateOn { get; set; }
        [Column("PPAPQty")]
        public int? Ppapqty { get; set; }
        [StringLength(50)]
        public string QualityContact { get; set; }
        [StringLength(50)]
        public string QualityContactPhone { get; set; }
        public long? EngineerId { get; set; }
        public long? DesignerId { get; set; }
        [StringLength(50)]
        public string ToolingPaidBy { get; set; }
        public double? TotalToolingCost { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? TotalDueDateOn { get; set; }
        public int? DesignValidationLevel { get; set; }
        public long? DeptCodeId { get; set; }
        [Required]
        [StringLength(50)]
        public string CountryOfOrigin { get; set; }
        [Column("IsSupPPAPRequired")]
        public byte IsSupPpaprequired { get; set; }
        public double CustomerSafetyStock { get; set; }
        public long FirstShipId { get; set; }
    }
}